// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cqtcxxavrzwfyttjgkrj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNxdGN4eGF2cnp3Znl0dGpna3JqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MjM2MTQsImV4cCI6MjA2NTI5OTYxNH0.nyb3TaiiSl2DcFmrZGDICnpE4gH6tTF5Kf4iQW1XVr0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);